[options.entry_points]
console_scripts =
    rclpy_image_publisher = test_rosidl_buffer.rclpy_image_publisher:main
    rclpy_image_subscriber = test_rosidl_buffer.rclpy_image_subscriber:main
    rclpy_legacy_image_publisher = test_rosidl_buffer.rclpy_legacy_image_publisher:main
    rclpy_legacy_image_subscriber = test_rosidl_buffer.rclpy_legacy_image_subscriber:main
    rclpy_parameter_types_service = test_rosidl_buffer.rclpy_parameter_types_service:main
    rclpy_parameter_types_client = test_rosidl_buffer.rclpy_parameter_types_client:main
    rclpy_image_pubsub = test_rosidl_buffer.rclpy_image_pubsub:main
    rclpy_fibonacci_action_server = test_rosidl_buffer.rclpy_fibonacci_action_server:main
    rclpy_fibonacci_action_client = test_rosidl_buffer.rclpy_fibonacci_action_client:main
